TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'TYPO3.TypoScript': TRUE
Lelesys:
  Plugin:
    IndexedSearch:
      # Default template paths. DO NOT remove these lines
      templateRootPath: 'resource://Lelesys.Plugin.IndexedSearch/Private/Templates/'


